version: '3'
name: moodle-php-bookworm
services:
  webserver:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:     
      - 'moodle_html:/var/www/html/'
      - 'moodle_data:/var/www/moodledata'  
volumes:
  moodle_html:
    driver: local
  moodle_data:
    driver: local
