services:
  mariadb:
    image: mariadb:10.11
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle_network
    restart: unless-stopped

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle_app
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepassword
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: Admin123!
      MOODLE_EMAIL: admin@example.com
      MOODLE_WWWROOT: http://localhost:8080
    ports:
      - "8080:80"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
    networks:
      - moodle_network
    restart: unless-stopped

  vpl-jail:
    image: my-vpl-jail:latest
    container_name: vpl_jail
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - vpl_jail_data:/etc/vpl
    networks:
      - moodle_network
    restart: unless-stopped

volumes:
  db_data:
  moodle_data:
  moodledata_data:
  vpl_jail_data:

networks:
  moodle_network:
    driver: bridge