version: '3.1'
name: pma
services:
  db:
#    image: mariadb:latest
    image: mysql:latest
#    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8mb4
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
